services:
  - type: web
    name: smartconvert-file-tools
    runtime: node
    plan: free
    rootDir: backend
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_VERSION
        value: 20
      - key: PUBLIC_KEY
        sync: false
      - key: SECRET_KEY
        sync: false
      - key: CLOUDCONVERT_KEY
        sync: false
